# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPagoenLineatest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pagoenLineatest(self):
    self.driver.get("https://orbi.edu.do/orbi/seguridad/usuario/inicio")
    self.driver.set_window_size(1936, 1056)
    element = self.driver.find_element(By.ID, "encabezado")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "MI MENÚ").click()
    self.driver.find_element(By.LINK_TEXT, "Caja").click()
    self.driver.find_element(By.LINK_TEXT, "Pago en línea").click()
    element = self.driver.find_element(By.LINK_TEXT, "Tutorial")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
