# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginTest(self):
    self.driver.get("https://orbi.edu.do/orbi/")
    self.driver.set_window_size(901, 645)
    self.driver.find_element(By.ID, "txtNombreUsuario").send_keys("joelmatos_123@hotmail.com")
    self.driver.find_element(By.ID, "txtContrasena").send_keys("...")
    self.driver.find_element(By.ID, "btnSesion").click()
  
